name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ["16"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x.x

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format

      - name: Lint
        run: pnpm run lint

      - name: Build Packages
        run: pnpm run build

      - uses: supabase/setup-cli@v1
        with:
          version: 1.5.0

      - name: Start Supabase
        run: SUPABASE_INTERNAL_IMAGE_REGISTRY=docker.io pnpm run start supabase

      - name: Run Tests
        run: pnpm run test
            