name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.x.x

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Start Supabase
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 5
          retry_on: error
          command: pnpm supabase start -x edge-runtime,logflare,vector,studio,imgproxy,pgadmin-schema-diff,migra,postgres-meta --ignore-health-check

      - name: 🦺 Check Format and Lint
        id: static
        run: pnpm run check

      - name: 📦 Build Packages
        id: build
        run: pnpm run build:packages

      - name: 🚧 Test 1
        id: test-1
        run: pnpm turbo run test --concurrency=1 --filter='!@supabase-cache-helpers/postgrest-swr' --filter='!@supabase-cache-helpers/postgrest-react-query'

      - name: 🚧 Test 2
        id: test-2
        run: pnpm run test
        working-directory: packages/postgrest-swr

      - name: 🚧 Test 3
        id: test-3
        run: pnpm run test
        working-directory: packages/postgrest-react-query

      - name: Upload postgrest-core coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/postgrest-core/coverage/coverage-final.json
          flags: postgrest-core
          fail_ci_if_error: false

      - name: Upload postgrest-react-query coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/postgrest-react-query/coverage/coverage-final.json
          flags: postgrest-react-query
          fail_ci_if_error: false

      - name: Upload postgrest-swr coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/postgrest-swr/coverage/coverage-final.json
          flags: postgrest-swr
          fail_ci_if_error: false

      - name: Upload storage-core coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/storage-core/coverage/coverage-final.json
          flags: storage-core
          fail_ci_if_error: false

      - name: Upload storage-swr coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/storage-swr/coverage/coverage-final.json
          flags: storage-swr
          fail_ci_if_error: false

      - name: Upload storage-react-query coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/storage-react-query/coverage/coverage-final.json
          flags: storage-react-query
          fail_ci_if_error: false

      - name: Check for error
        if: steps.static.outcome != 'success' || steps.build.outcome != 'success' || steps.test.outcome != 'success'
        run: exit 1
